#!/usr/bin/env racket
#lang racket

(require "src/state.rkt"
         "src/repl.rkt"
         "src/strings.rkt")

; welcome message
(display (get-string 'intro))

; initial state
(repl/handler "restart")

; start repl
(repl/loop)
