#!/usr/bin/env racket
#lang racket

(require "src/repl.rkt"
         "src/strings.rkt")

(display (get-string 'intro))

(with-handlers
  ; quit gracefully when Ctrl-C or SIGINT is received
  ([exn:break? (λ (_) (begin (newline) (repl/handler "quit")))])

  (repl/handler "restart")

  (repl/loop))
